name: 'resource-for-azure'

on: [workflow_dispatch]

permissions: write-all

jobs:
  ARM:
    name: 'Azure-env'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure-connect
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} -t ${{ secrets.TENANT_ID }}
      
#     - name: Run Arm
#       uses: azure/arm-deploy@v1
#       with: 
#         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ secrets.AZURE_RG }}
#         template: ./v-net.json
#     - name: Azure run
#       run : |
#         az network vnet create \
#         --name v-netber \
#         --resource-group user_KPLMMZYKUL_ResourceGroup \
#         --subnet-name subnet-1 --subnet-prefixes 10.0.1.0/24
        
    - name: Terraform Init
      run: terraform init 
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false
      continue-on-error: true
      
#     - name: Terraform Plan Status
#       if: steps.plan.outcome == 'failure'
#       run: "exit 1"
    
#     - name: Terraform Apply
#       run: terraform apply -auto-approve -input=false
