name: 'resource-for-azure'

on: [workflow_dispatch]

permissions: write-all

jobs:
  ARM:
    name: 'Azure-env'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure-connect
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} -t ${{ secrets.TENANT_ID }}
      
    - name: Run Arm
      uses: azure/arm-deploy@v1
      with: 
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./v-net.json
